extends: default

yaml-files:
  - "*.yaml"
  - "*.yml"

rules:
  document-start: disable
  truthy: disable
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  comments:
    min-spaces-from-content: 1
