# SENSORS – ELECTRICITY

# Virtual electricity power (W)
- platform: template
  sensors:
    virtual_electricity_power:
      friendly_name: "Virtual Electricity Power"
      unit_of_measurement: "W"
      entity_id:
        - light.energy_lights_no_power
        - switch.energy_switches_no_power_sensor
      value_template: >
        {% set ns = namespace(total=0) %}

        {# 1) Lights & switches without real power sensors (using assumed_watt) #}
        {% for e in expand('light.energy_lights_no_power', 'switch.energy_switches_no_power_sensor') %}
          {% set watt = state_attr(e.entity_id, 'assumed_watt') | float(0) %}
          {% if e.state == 'on' %}
            {% set ns.total = ns.total + watt %}
          {% endif %}
        {% endfor %}

        {{ ns.total }}


# Integration sensors – convert power → energy (kWh)
- platform: integration
  source: sensor.virtual_electricity_power
  name: "Virtual Electricity Energy"
  unit_prefix: k
  round: 3

- platform: integration
  source: sensor.energy_real_power_sensors_w
  name: "Real Electricity Energy"
  unit_prefix: k
  round: 3

