# SENSORS – HEATING (TEMPLATE SENSORS)

- platform: template
  # Update every minute so the counter increments
  scan_interval: 60
  sensors:

    bedroom_heater_heating_minutes:
      friendly_name: "Bedroom Heater Heating Minutes"
      unique_id: bedroom_heater_heating_minutes
      unit_of_measurement: "min"
      device_class: duration
      value_template: >
        {% set last = states('sensor.bedroom_heater_heating_minutes') | float(0) %}
        {% if is_state('binary_sensor.bedroom_heater_active', 'on') %}
          {{ last + 1 }}
        {% else %}
          {{ last }}
        {% endif %}
      icon_template: mdi:radiator

    office_heater_heating_minutes:
      friendly_name: "Office Heater Heating Minutes"
      unique_id: office_heater_heating_minutes
      unit_of_measurement: "min"
      device_class: duration
      value_template: >
        {% set last = states('sensor.office_heater_heating_minutes') | float(0) %}
        {% if is_state('binary_sensor.office_heater_active', 'on') %}
          {{ last + 1 }}
        {% else %}
          {{ last }}
        {% endif %}
      icon_template: mdi:radiator
